### PR TITLE
Add FRC Nexus Integration to get team lineups

### PR DESCRIPTION
**Pull request by FletcherS7**
frc.nexus Integration to pull team lineups for practice matches and playoffs.

Caveats that need to be addressed.
js file uses static value for event code, this should be automated before merging.

For playoffs the scorekeeper must be logged into Nexus with scorekeeper permissions, this is because the lineups are considered privileged and are not in the public API.

### CODE REVIEW

**Comment by patfair** [comment]
Thanks. I'll play around with this a bit more before merging.

**Comment by patfair** [comment]
I'm actually finding that I can access the API without any permissions:
```
$ curl https://api.frc.nexus/v1/2023cc/sf13/lineup
{"red":["6036","2046","5940"],"blue":["5460","1619","2910"]}
```

So I think I will actually rewrite this such that it all happens server-side, automatically, when the match is loaded.

**Comment by patfair** [comment]
Hey @eforbes, I'd appreciate your opinion here -- this is what I am thinking of doing:

1. Adding a boolean setting to Cheesy Arena to enable Nexus integration
2. When a practice or playoff match is loaded, the Cheesy Arena server hits the Nexus API to get the lineup
3. The teams are substituted in transparently to the scorekeeper and field staff, so they don't need to do anything at all

Does that sound reasonable? Does this API used in @FletcherS7's PR require auth for matches that haven't been played yet? If so, would it be possible to have a token that we can save into the Cheesy Arena settings per event rather than relying on JS and cookies?

**Comment by eforbes** [comment]
SGTM

The API endpoint does not require any auth, but due to the lineup confidentiality it will not return playoff lineups until the queuer has marked the match as "on field".

One edge case here might be for the first playoff match or the first match after a break- lineups might not be set the first time the scorekeeper loads the match. As long as they have a way to reload it though that should be fine. It would be nice for the scorekeeper to have an indicator to know whether the lineups were loaded from Nexus or if it is just showing the default (so they know to check with the queuer and reload once they are set).

**Comment by patfair** [comment]
Oh yeah, good point about potentially loading the match before the lineup is in. I guess if the scorekeeper knows to reload it when the teams are approaching everything will be fine.

**Comment by patfair** [comment]
Done in 7fe23ed88132aa3dc59d2832903017792b2454d3.

**Comment by FletcherS7** [comment]
If FRC Nexus dos not supply team lineups, CheesyArena loads loads a match with blank for each of the teams.

Suggested behavior should be to use the default lineup if FRC Nexus does not supply a lineup.

**Comment by patfair** [comment]
Can you capture what the response from Nexus is in this scenario?

**Comment by eforbes** [comment]
The API will return an empty json object. It's also possible if the queuer hasn't entered in one of the lineups, the response will not include one of "red" or "blue"

**Pull request closed without merging**
