### PR TITLE
Use proper match abort sound

### PR DESCRIPTION
**Pull request by Ewpratten**
I noticed while watching chezy champs that some of the sounds weren't the ones used in actual FRC games. It seems that the proper file for *match abort* was never used. So this pull request replaces the current sound with the one used in the FIRST FMS.

### CODE REVIEW

**Comment by FletcherS7** [comment]
We choose not to use the official FIRST sounds

**Comment by Ewpratten** [comment]
Oh. Why the other ones then?

**Comment by FletcherS7** [comment]
These are simply the files chosen for Chezy Champs. Any event that uses Cheesy Arena is free to replace the sound files with any they like.

**Comment by Ewpratten** [comment]
Ok. Then I should probably close this PR. Maybe there could be a section in
setup that allows the user to upload their own sounds with a frontend?

**Comment by ejordan376** [comment]
All you have to do is swap out the files in /static/audio/.  Probably doesn’t need to be on the front end.

**Comment by Ewpratten** [comment]
Ok

**Pull request closed without merging**
