### PR TITLE
Updated field monitor

### PR DESCRIPTION
**Pull request by ejordan376**
Added fuchsia to team background options to indicate robot radio linked with out rio.

@FletcherS7 Here it is.

### CODE REVIEW

**Comment by FletcherS7** [comment]
Thank you @ejordan376

**Comment by patfair** [comment]
Just curious, where does this data come from? How does the driver station know if the radio is linked if it's not yet getting any packets from the roboRIO?

**Comment by FletcherS7** [comment]
According to the FMS Documentation. The Driver Station is checking for a connection to the robot radio at 10.TE.AM.1

**Comment by patfair** [comment]
Got it. I'm wondering if this might be confusing/redundant then with the other source of radio link data I recently added, by looking at the state of the AP itself. The AP method has the advantage of knowing if the radio is connected even if the DS isn't.

**Comment by FletcherS7** [comment]
One tells us if the AP is talking to the radio well the other tells us if the DS is talking to the radio. Both are useful.

**Comment by Ewpratten** [comment]
@FletcherS7 is the documentation that you are referring to the [FMS Whitepaper](https://wpilib.screenstepslive.com/s/fms/m/whitepaper/l/608744-fms-whitepaper)?

**Pull request merged**
