### PR TITLE
Add team list for alliance selection

### PR DESCRIPTION
**Pull request by legoktm**
So teams and announcers can still see who is available. We used this at CalGames 2016.

### CODE REVIEW

**Comment by patfair** [comment]
I like how you implemented this change, but could you please make whether to display it or not an option in the settings?

We on 254 don't like it when unprepared alliance captains just pick off the list (and sometimes get good teams by dumb luck) so we wouldn't use it at Chezy Champs.

**Comment by legoktm** [comment]
Heh, alright. What would you like the default setting to be?

**Comment by patfair** [comment]
I don't care that much, but I guess I'd like to encourage other events to
follow our philosophy, so default off?

**Comment by legoktm** [comment]
Sorry about letting this sit for so long. I've rebased it against master and made it a configurable setting (default false).

**Comment by patfair** [comment]
It looks like there might be an overlap issue when using four-team alliances. Maybe you could limit it to three columns, or remove (or make smaller) the ranking numbers (which would also help with distinguishing them from team numbers)?
screen shot 2017-10-10 at 8 51 51 pm

**Comment by patfair** [comment]
Closing since this finally got implemented in https://github.com/Team254/cheesy-arena/pull/188.

**Pull request closed without merging**
