### PR TITLE
Add 2024 game specific warning audio

### PR DESCRIPTION
**Pull request by FletcherS7**

### CODE REVIEW

**Comment by patfair** [comment]
Based on the complaints here I was planning on just leaving the steam whistle in: https://www.chiefdelphi.com/t/favorite-clever-match-start-phrases/464888/16

**Comment by geekygirlsarah** [comment]
Could an option be added to choose which sound (like "classic endgame whistle" vs "Crescendo endgame riff")?

**Comment by FletcherS7** [comment]
@patfair Maybe include both files and default to the Rift? That way the baseline configuration for CheesyArena is that of the official season, but events are free to switch out the file for the includes train whistle (or their own sound files)

**Comment by patfair** [comment]
Okay, I added the guitar riff as default but kept the steam whistle file around. I also boosted the volume a bit.

**Pull request closed without merging**
